FROM node:16

ARG VITE_BACKEND_URL
ARG VITE_API_ENDPOINT

ENV VITE_BACKEND_URL=${VITE_BACKEND_URL}
ENV VITE_API_ENDPOINT=${VITE_API_ENDPOINT}

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . /app/
CMD ["npm", "run", "dev"]


